### ISSUE TITLE
[Question] Time to read on Series page

### ISSUE THREAD

**Issue by petesharpnz** [GinoPane/oc-blogtimetoread-plugin#3]
Is it possible to display the time to read for a post on a series page?  It works really well on the post page.  thanks.

**Comment by GinoPane** [comment]
Sure! 
Actually, it is up to you where to show it. Basically, you can use post property to show the time (in minutes by default).

Refer to README:
1) {{ post.timeToRead }}
2) {{ post.content | timeToRead(100, false) }}

So in your theme template when you loop through your posts you can show their time to read when you want and in a way you prefer. It depends on the theme you use etc.

**Comment by GinoPane** [comment]
This is going to be closed in a day due to inactivity.
